#!/sbin/runscript
# Copyright 1999-2002 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /usr/local/ssd/gentoo-x86/output/x11-misc/cvs-repo/gentoo-x86/x11-misc/synaptics/files/Attic/rc.init,v 1.3 2004/07/07 20:01:15 battousai Exp $

depend() {
	use localmount
}

start() {
	ebegin "Starting syndaemon"
	syndaemon ${SYNDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping syndaemon"
	kill `cat /var/run/syndaemon.pid`
	eend $?
}
