#!/bin/sh
# gentoo qmail rc file to start qmail-start and thus qmail-send
# $Header: /usr/local/ssd/gentoo-x86/output/net-mail/cvs-repo/gentoo-x86/net-mail/qmail/files/Attic/rc,v 1.1 2003/11/30 11:32:06 robbat2 Exp $

exec env - PATH="/var/qmail/bin:$PATH" \
	qmail-start "`grep -v '^#' /var/qmail/control/defaultdelivery`"
