#!/bin/sh
# Gentoo qmail rc booter
# $Header: /usr/local/ssd/gentoo-x86/output/net-mail/cvs-repo/gentoo-x86/net-mail/qmail/files/Attic/run-qmailsend,v 1.1 2003/11/30 11:32:06 robbat2 Exp $
exec /var/qmail/rc
