#!/bin/bash
# Gentoo qmail rc booter
# $Header: /usr/local/ssd/gentoo-x86/output/mail-mta/cvs-repo/gentoo-x86/mail-mta/qmail/files/Attic/run-qmailsend,v 1.3 2005/01/03 20:55:10 hansmi Exp $
exec /var/qmail/rc
