#!/bin/sh
# Gentoo qmail rc booter
# $Header: /usr/local/ssd/gentoo-x86/output/mail-mta/cvs-repo/gentoo-x86/mail-mta/qmail/files/Attic/run-qmailsend,v 1.2 2004/07/18 03:29:51 dragonheart Exp $
exec /var/qmail/rc
