#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /usr/local/ssd/gentoo-x86/output/x11-misc/cvs-repo/gentoo-x86/x11-misc/afbinit/files/afbinit.init,v 1.1 2003/07/08 20:33:25 weeve Exp $

depend() {
    before xdm
}

start() {
    ebegin "Loading afbinit"
    /usr/sbin/rc.afb
    eend $? "Failed to load afbinit"
}
