#!/bin/bash
# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /usr/local/ssd/gentoo-x86/output/games-action/cvs-repo/gentoo-x86/games-action/phobiaiii/files/Attic/playphobiaIII,v 1.1 2003/09/10 19:29:16 vapier Exp $

cd /opt/phobiaiii
./phobia3
