#!/bin/sh
# Init script for qmail-send
# Copied from LWQ
# $Header: /usr/local/ssd/gentoo-x86/output/mail-mta/cvs-repo/gentoo-x86/mail-mta/qmail-ldap/files/Attic/run-qmail-send,v 1.1 2007/06/16 13:48:10 hollow Exp $
exec env - PATH="/var/qmail/bin:$PATH" \
	qmail-start "`cat /var/qmail/control/defaultdelivery`"
